### ISSUE TITLE
Official image in dockerhub

### ISSUE THREAD

**Issue by moonming** [apache/incubator-apisix-docker#15]
https://docs.docker.com/docker-hub/official_images/
we need to add the official image of APISIX in dockerhub.

**Comment by hiproz** [comment]
1. i think we can ref from the alpine or centos version image of this repo 
2. i think we shoud provide an official image that include the apisix  etcd and dashbord

**Comment by hiproz** [comment]
i can try this work from the 1.1 version of apisix  if that is possible :)

**Comment by moonming** [comment]
@hiproz The official image in dockerhub is here: https://hub.docker.com/r/apache/apisix, which is binding with this repo.

> i think we shoud provide an official image that include the apisix etcd and dashbord

It's good for beginner, welcome PR.
