### ISSUE TITLE
No existing manifest. lua-resty-template-1.9-1.src.rock

### ISSUE THREAD

**Issue by jiagoumengxiang** [apache/incubator-apisix-docker#33]
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/lua-resty-template-1.9-1.src.rock

No existing manifest. Attempting to rebuild...

Error: Could not satisfy dependency lua-resty-etcd 0.7: No results matching query were found for Lua 5.1.

**Comment by chnliyong** [comment]
Pls supply more details about how you get this error, thanks!

**Comment by membphis** [comment]
You can make a try now. I think it should be fine now.

https://raw.githubusercontent.com is already accessible, this is a network issue.
