### ISSUE TITLE
Access 8080 port has response "404 Not Found"

### ISSUE THREAD

**Issue by RuizhaoLee** [apache/incubator-apisix-docker#36]
I use docker to start apisix, and then visit http://127.0.0.1:8080. The response is "404 not found".
Do you have a built-in dashboard in the docker image of apsix?

My command to start the apinix container is as follows
```shell
docker run --name test-api-gateway -v ${PWD}/example/apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml -v ${PWD}/example/apisix_log:/usr/local/apisix/logs --link etcd-server -p 8080:9080 -p 8083:9443 -d iresty/apisix
```

![image](https://user-images.githubusercontent.com/35215628/75210231-7c0dc700-57bb-11ea-9a75-5e007dee7f73.png)

**Comment by hiproz** [comment]
1. as your case ,u use the default router of nginx  ,pls check the nginx default conf file adn /usr/local/apisix/dashborad  of iresty/apisix
2. i suggest that u should use the docker image of this project

**Comment by moonming** [comment]
@RuizhaoLee the docker image not has built-in dashboard, we will fix it in next release.
