### ISSUE TITLE
etcd-server could not be resolved (3: Host not found)

### ISSUE THREAD

**Issue by to2false** [apache/incubator-apisix-docker#42]
I created a network named gateway, then let ectd-server and test-api-gateway joined this network.

```
docker exec -it test-api-gateway sh
```
```
/usr/local/apisix # ping etcd-server
PING etcd-server (172.19.0.2): 56 data bytes
64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.272 ms
64 bytes from 172.19.0.2: seq=1 ttl=64 time=0.071 ms
64 bytes from 172.19.0.2: seq=2 ttl=64 time=0.068 ms
64 bytes from 172.19.0.2: seq=3 ttl=64 time=0.116 ms
64 bytes from 172.19.0.2: seq=4 ttl=64 time=0.078 ms
64 bytes from 172.19.0.2: seq=5 ttl=64 time=0.066 ms
```

But got error as the title after request
```
curl http://127.0.0.1:8080/apisix/admin/services/1 -X PUT -d '
{
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:9081": 1
        }
    }
}'
{"error_msg":"etcd-server could not be resolved (3: Host not found)"}
```
-------
**Specify ip works**

**Comment by linsir** [comment]
You should change the etcd address to `etcd-server` in [config.yaml](https://github.com/apache/incubator-apisix/blob/master/conf/config.yaml#L117)

**Comment by to2false** [comment]
@linsir I changed it, If not, I won't get this error

**Comment by linsir** [comment]
Try add  127.0.0.11 to `dns_resolver` in [config.yaml](https://github.com/apache/incubator-apisix/blob/master/conf/config.yaml#L83)

**Comment by to2false** [comment]
it works, thx

**Comment by izayoi-akira** [comment]
> it works, thx

How to configure this

**Comment by to2false** [comment]
@izayoi-akira https://github.com/apache/apisix-docker/issues/42#issuecomment-613324796 the above reply explains the steps
