### ISSUE TITLE
The host networking driver is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.

### ISSUE THREAD

**Issue by jeremyyin2012** [apache/incubator-apisix-docker#8]
docker-apisix docker-compose.yml using `network_mode: host` now, but the host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server. see [https://docs.docker.com/network/host/](https://docs.docker.com/network/host/)

`network_mode: host` used for best network performance, but if you run docker environment for development or quick demo on Mac/Windows, it's not working.

This means we can't access the container service from the current machine when you start services by using `network_mode: host` on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.

Maybe a solution, and this is what I have tried:

Change docker-compose.yml to using `ports` and `networks`

```
    ports:
      - "9080:9080"
      - "9443:9443"
    networks:
      - apisix
    # network_mode: host
```

And then should edit config.yml, add allow ips, change etcd host to using container service name

```
  allow_admin:
    - 127.0.0.0/24
    - 192.168.0.0/16

etcd:
  # host: "http://127.0.0.1:2379"
  host: "http://etcd:2379"
```

**Comment by moonming** [comment]
@vkill please take a look.
@jeremyyin2012 PR is welcome:)

**Comment by vkill** [comment]
Oh,  I have just knew that it's only works on linux. As a example, should change it to NAT mode.

**Comment by frozensoft** [comment]
Also should add a dns_resolver to config.yml, otherwise apisix will not able to resolve `etcd`.
```
dns_resolver:
    - 127.0.0.11
```
